### ISSUE TITLE
write proper comments for every functions

### ISSUE THREAD

**Issue by Ashutosh6393** [Ashutosh6393/password_gen_mannager#1]
For example: If the function is regarding 'saving the password in database' then write a proper comment explaining the use of that function.

**Comment by Sagargajare** [comment]
@Ashutosh6393 I would like to contribute to this project. Can you assign this issue to me?

**Comment by adityalahariya** [comment]
@Ashutosh6393 Hey i would like to contribute to this project. Can you assign this issue to me?

**Comment by Sagargajare** [comment]
@Ashutosh6393 I opened the pr. please review it.
